### ISSUE TITLE
Get connection this system and google spreadsheet

### ISSUE THREAD

**Issue by yusuko** [ookamiinc/twitter-analytics-acquirer#3]
# What
 - create process to send created file to spreadsheet
 
 # Summary
  - I use Google drive API.

**Comment by yusuko** [comment]
download Google API
 - reference https://www.virment.com/google-drive-api-activate/

**Comment by yusuko** [comment]
http://wordpress.honobono-life.info/code/ruby%E3%81%A7%E6%97%A2%E5%AD%98%E3%81%AE%E3%82%A8%E3%82%AF%E3%82%BB%E3%83%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E8%BF%BD%E5%8A%A0/

**Comment by yusuko** [comment]
CSVでデータが取れる。
→それをパース(ブロックを作る)
→それを表に埋めていく。

1行目は[1,1] ~ [1,x]
2行目以降は[i,1]~[i,x] (ループ。++i)
参考
```ruby
i=2
ary_rows.each do |row|
  sheet1[i,1] = row[0].to_i
  sheet1[i,2] = row[1].to_i
  sheet1[i,3] = row[2].to_i 
  sheet1[i,4] = row[3].to_i
  i += 1
end
```

**Comment by yusuko** [comment]
To do

- まずはconsoleの修正
   - done

 - パースについてもう1回復習。
→APIのコードを復習。もしかしたら必要なgemがあるかも。
 - require 'csv'
 - CSV.parse(file, headers:true)とかで良さそう。(headers:true)なくても良いけど。
→done

- mechanizeはファイルがバイナリで表示される。テキストに変換させる必要がある。
→done

 - その後、ループ処理を書く。
→done

**Comment by yusuko** [comment]
サンプルコード。
実際にかけた。

```ruby
    array = [1, 2, 3]
    o = 2
    array.each do |a|
      ws[o,1]= a
      ws[o,2]= a
      ws[o,3]= a
      o += 1
    end
```

**Comment by yusuko** [comment]
- ファイルが取れる時と取れない時がある
- 自動実行
   - be rubyで実行できることを確認。
    - cronを使う。
       - cdで移動
       - be ruby

この２つかな。

**Comment by yusuko** [comment]
自動実行参考url
 - using 'whenever'
    - github https://github.com/javan/whenever
    - 参考記事 http://opiyotan.hatenablog.com/entry/rails-whenever
  - 定期実行そのものはできた。
  - あとはどうやってスクリプトを実行するのか。lib/taskらへんに置くのがいいのかな？

**Comment by yusuko** [comment]
必要なファイル
- gem関係
- 実行するscript
- task管理のファイル
- whenever制御のファイル
- logを出力するファイル

**Comment by yusuko** [comment]
@nafu  @ladnack

Please check the code.(in master)
It's OK when you have enough time, because it seems that you are busy recently.

I'm so sorry not to create PR when developing.
I think it's hard to review code in master, so I am considering way.

Below is the memo when developing.

###  What I am doing
 Scraping
1. login to twitter
2. get data about twitter_analytics(CSV)
3. Parse CSV
4. Write them to spreadsheets
5. Run crontab using 'whenever' gem( to run automatically)

 Useless files
I have a lot of useless forms because I use rails framework first.
But I think it has more priority to run earlier than minimizing it. So I will change them to ruby code later.

**Comment by sakatore** [comment]
You can refer the following about writing to spreadsheet and authentication.

* https://github.com/ookamiinc/api/pull/3545/files#diff-cd30fe5386308f6f4aa6d04bdae37e98
* https://github.com/ookamiinc/api/issues/3591

**Comment by yusuko** [comment]
Thank you!
I'll check it later.

**Comment by yusuko** [comment]
@ladnack 
I remove auth information from commit.(Though commit is not good now.I fix and arrange commit later)

**Comment by yusuko** [comment]
>You can refer the following about writing to spreadsheet and authentication.
https://github.com/ookamiinc/api/pull/3545/files#diff-cd30fe5386308f6f4aa6d04bdae37e98
ookamiinc/api#3591

I checked links. Thank you.
But I think we can send data to spreadsheets using only `google_drive` gem.
Please tell me if it is not enough.
